name:          Руководство по написанию кода от @mdo
description:   Стандарты для разработчки гибких, прочных и устойчивых HTML и CSS.
url:           http://mdo.github.com/code-guide

markdown:      rdiscount
permalink:     pretty
pygments:      true
